[package]
name = "recast-detour-sys"
version = "0.1.0"
authors = ["Edwin Cheng <edwin0cheng@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
insta = "0.7.4"

[build-dependencies]
cmake = "0.1"

[features]
skip-build-recast = []
default = []
